repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: ["--select", "I",
              "--select", "E",
              "--select", "W",
              "--select", "N",
              "--select", "UP",
              "--select", "A",
              "--select", "B",
              "--select", "ISC",
              "--select", "RUF",
              "--select", "NPY",
              "--select", "PD",
              "--ignore", "E501",
              --fix]
        exclude: \.ipynb$
      - id: ruff-format
        types_or: [python, pyi, jupyter]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        args: [--strict, --ignore-missing-imports]
        exclude: \.ipynb$
        additional_dependencies: [types-pyyaml, hydra-core, wandb]
