defaults:
  - _self_

project_name: "PlantClef2025"

project_path: "/mnt/storage1/shared_data/plant_clef_2025/"

data:
  folder: "data/"
  metadata_file: "PlantCLEF2024_single_plant_training_metadata.csv"
  species_file: "species_ids.csv"
  test_folder: "plant_clef_2025_test/"
  test_images_folder: "PlantCLEF2025_test_images/PlantCLEF2025_test_images/"

models:
  name: "vit_base_patch14_reg4_dinov2.lvd142m"
  pretrained: false
  folder: "models/"
  checkpoint_file: "model_onlyclassifier_then_all/model_best.pth.tar"

submission_file: "submission.csv"

seed: 42
