defaults:
  - _self_

project_name: "PlantClef2025"

project_path: "/mnt/storage1/shared_data/plant_clef_2025/"

data:
  folder: "data/"
  metadata:
    folder: "metadata/"
    training: "PlantCLEF2024_single_plant_training_metadata.csv"
    test: "PlantCLEF2025_test.csv"
    no_label: "pseudoquadrats_without_labels_complementary_training_set_urls.csv"
  train_folder: "plant_clef_train_281gb/"
  test_folder: "plant_clef_2025_test/"
  test_images_folder: "PlantCLEF2025_test_images/PlantCLEF2025_test_images/"
  utils:
    folder: "utils/"
    plant_taxonomy_file: "plant_taxonomy.pkl"
    organ_hierarchy_file: "organ_hierarchy.csv"
    genus_mapping: "genus_ids.csv"
    family_mapping: "family_ids.csv"
    organ_mapping: "organ_ids.csv"
    species_mapping: "species_names.csv"
  other:
    folder: "other/"
  combine_classes_threshold: 0 # The minimum number of images required for a class the get its own label

models:
  name: "vit_base_patch14_reg4_dinov2.lvd142m"
  pretrained: false
  folder: "models/"
  checkpoint_file: "model_onlyclassifier_then_all/model_best.pth.tar"
  save:
    folder: "saved_models/5heads_all_labels_vit_base_patch14_reg4_dinov2.lvd142m"
    every: 1000

training:
  use_all_data: false # if true, use all data for training
  val_size: 0.05
  test_size: 0.1
  batch_size: 144
  shuffle: True
  num_workers: 1
  min_score: 0.1
  top_k_tile: 2
  lr: 1e-4
  epochs: 1
  loss_weights:
    species: 1.0
    genus: 1.0
    family: 1.0
    plant: 1.0
    organ: 1.0

evaluating:
  every: 1000
  batch_size: 144
  shuffle: True
  num_workers: 8

image_width: 518
image_height: 518

submission_file: "submission.csv"

seed: 42
